import urllib
import xml.etree.ElementTree as ET

service_url='http://python-data.dr-chuck.net/comments_42.xml'

data='''
<commentinfo>
  <note>This file contains the actual data for your assignment - good luck!</note>

  <comments>
    <comment>
       <name>Jock</name>
       <count>100</count>
    </comment>
    <comment>
       <name>Johann</name>
       <count>98</count>
    </comment>
    <comment>
       <name>Fahad</name>
       <count>97</count>
    </comment>
    <comment>
       <name>Michee</name>
       <count>97</count>
    </comment>
    <comment>
       <name>Hussnan</name>
       <count>94</count>
    </comment>
    <comment>
       <name>Praise</name>
       <count>94</count>
    </comment>
    <comment>
       <name>Danny</name>
       <count>93</count>
    </comment>
    <comment>
       <name>Jenah</name>
       <count>91</count>
    </comment>
    <comment>
       <name>Guinevere</name>
       <count>88</count>
    </comment>
    <comment>
       <name>Satveer</name>
       <count>87</count>
    </comment>
    <comment>
       <name>Dania</name>
       <count>85</count>
    </comment>
    <comment>
       <name>Queeneffa</name>
       <count>85</count>
    </comment>
    <comment>
       <name>Monique</name>
       <count>81</count>
    </comment>
    <comment>
       <name>Pasquale</name>
       <count>78</count>
    </comment>
    <comment>
       <name>Lloyd</name>
       <count>78</count>
    </comment>
    <comment>
       <name>Keo</name>
       <count>77</count>
    </comment>
    <comment>
       <name>Pipa</name>
       <count>74</count>
    </comment>
    <comment>
       <name>Kate</name>
       <count>72</count>
    </comment>
    <comment>
       <name>Subhaan</name>
       <count>69</count>
    </comment>
    <comment>
       <name>Lybi</name>
       <count>65</count>
    </comment>
    <comment>
       <name>Ramanas</name>
       <count>64</count>
    </comment>
    <comment>
       <name>Ruben</name>
       <count>63</count>
    </comment>
    <comment>
       <name>Cesare</name>
       <count>60</count>
    </comment>
    <comment>
       <name>Pele</name>
       <count>57</count>
    </comment>
    <comment>
       <name>Robin</name>
       <count>53</count>
    </comment>
    <comment>
       <name>Mueez</name>
       <count>52</count>
    </comment>
    <comment>
       <name>Aoibhe</name>
       <count>51</count>
    </comment>
    <comment>
       <name>Rhia</name>
       <count>49</count>
    </comment>
    <comment>
       <name>Suheyb</name>
       <count>43</count>
    </comment>
    <comment>
       <name>Jude</name>
       <count>43</count>
    </comment>
    <comment>
       <name>Morvern</name>
       <count>41</count>
    </comment>
    <comment>
       <name>Ifrah</name>
       <count>41</count>
    </comment>
    <comment>
       <name>Abar</name>
       <count>37</count>
    </comment>
    <comment>
       <name>Cristian</name>
       <count>36</count>
    </comment>
    <comment>
       <name>Ismaeel</name>
       <count>36</count>
    </comment>
    <comment>
       <name>Ava</name>
       <count>34</count>
    </comment>
    <comment>
       <name>Shafaq</name>
       <count>33</count>
    </comment>
    <comment>
       <name>Kaidenn</name>
       <count>30</count>
    </comment>
    <comment>
       <name>Serene</name>
       <count>30</count>
    </comment>
    <comment>
       <name>Enoghado</name>
       <count>28</count>
    </comment>
    <comment>
       <name>Marina</name>
       <count>28</count>
    </comment>
    <comment>
       <name>Kiefer</name>
       <count>27</count>
    </comment>
    <comment>
       <name>Hubert</name>
       <count>24</count>
    </comment>
    <comment>
       <name>Yusef</name>
       <count>19</count>
    </comment>
    <comment>
       <name>Karla</name>
       <count>16</count>
    </comment>
    <comment>
       <name>Coco</name>
       <count>14</count>
    </comment>
    <comment>
       <name>Makala</name>
       <count>11</count>
    </comment>
    <comment>
       <name>Alfred</name>
       <count>7</count>
    </comment>
    <comment>
       <name>Malika</name>
       <count>5</count>
    </comment>
    <comment>
       <name>Leigha</name>
       <count>2</count>
    </comment>
  </comments>
</commentinfo>
'''
#print data
tree=ET.fromstring(data)

results=(tree.findall('comments'))[0]
#print len(results)
results=results.findall('comment')
print sum(int(results[i].find('count').text) for i in range(len(results)))
#results[0].find('comment').find('count').text
#print val
